# Generated by Django 2.1.5 on 2019-02-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='country',
        ),
    ]
